Original*       163.com         
Bitsquatting    063.com         
Bitsquatting    363.com         
Bitsquatting    563.com         
Bitsquatting    963.com         
Bitsquatting    q63.com         
Bitsquatting    173.com         
Bitsquatting    143.com         
Bitsquatting    123.com         
Bitsquatting    1v3.com         
Bitsquatting    162.com         
Bitsquatting    161.com         
Bitsquatting    167.com         
Bitsquatting    16s.com         
Transposition   613.com         
Transposition   136.com         
Replacement     263.com         
Replacement     q63.com         
Replacement     173.com         
Replacement     1y3.com         
Replacement     1t3.com         
Replacement     153.com         
Replacement     164.com         
Replacement     16e.com         
Replacement     16w.com         
Replacement     162.com         
Omission        63.com          
Omission        16.com          
Omission        13.com          
Hyphenation     1-63.com        
Hyphenation     16-3.com        
Insertion       1763.com        
Insertion       1673.com        
Insertion       1y63.com        
Insertion       16y3.com        
Insertion       1t63.com        
Insertion       16t3.com        
Insertion       1563.com        
Insertion       1653.com        
Subdomain       1.63.com        
Subdomain       16.3.com        
