Original*       ask.com         
Bitsquatting    csk.com         
Bitsquatting    esk.com         
Bitsquatting    isk.com         
Bitsquatting    qsk.com         
Bitsquatting    ark.com         
Bitsquatting    aqk.com         
Bitsquatting    awk.com         
Bitsquatting    ack.com         
Bitsquatting    a3k.com         
Bitsquatting    asj.com         
Bitsquatting    asi.com         
Bitsquatting    aso.com         
Bitsquatting    asc.com         
Repetition      askk.com        
Repetition      aask.com        
Repetition      assk.com        
Transposition   sak.com         
Transposition   aks.com         
Replacement     qsk.com         
Replacement     wsk.com         
Replacement     ssk.com         
Replacement     zsk.com         
Replacement     aek.com         
Replacement     adk.com         
Replacement     axk.com         
Replacement     azk.com         
Replacement     aak.com         
Replacement     awk.com         
Replacement     aso.com         
Replacement     asl.com         
Replacement     asm.com         
Replacement     asj.com         
Replacement     asi.com         
Omission        sk.com          
Omission        as.com          
Omission        ak.com          
Hyphenation     a-sk.com        
Hyphenation     as-k.com        
Insertion       aesk.com        
Insertion       asek.com        
Insertion       adsk.com        
Insertion       asdk.com        
Insertion       axsk.com        
Insertion       asxk.com        
Insertion       azsk.com        
Insertion       aszk.com        
Insertion       aask.com        
Insertion       asak.com        
Insertion       awsk.com        
Insertion       aswk.com        
Subdomain       a.sk.com        
Subdomain       as.k.com        
