Original*       cnn.com         
Bitsquatting    bnn.com         
Bitsquatting    ann.com         
Bitsquatting    gnn.com         
Bitsquatting    knn.com         
Bitsquatting    snn.com         
Bitsquatting    con.com         
Bitsquatting    cln.com         
Bitsquatting    cjn.com         
Bitsquatting    cfn.com         
Bitsquatting    cno.com         
Bitsquatting    cnl.com         
Bitsquatting    cnj.com         
Bitsquatting    cnf.com         
Homoglyph       cmn.com         
Homoglyph       cmm.com         
Homoglyph       cnm.com         
Repetition      ccnn.com        
Repetition      cnnn.com        
Transposition   ncn.com         
Replacement     xnn.com         
Replacement     dnn.com         
Replacement     fnn.com         
Replacement     vnn.com         
Replacement     cbn.com         
Replacement     chn.com         
Replacement     cjn.com         
Replacement     cmn.com         
Replacement     cnb.com         
Replacement     cnh.com         
Replacement     cnj.com         
Replacement     cnm.com         
Omission        cn.com          
Omission        nn.com          
Hyphenation     c-nn.com        
Hyphenation     cn-n.com        
Insertion       cbnn.com        
Insertion       cnbn.com        
Insertion       chnn.com        
Insertion       cnhn.com        
Insertion       cjnn.com        
Insertion       cnjn.com        
Insertion       cmnn.com        
Insertion       cnmn.com        
Subdomain       c.nn.com        
Subdomain       cn.n.com        
