Original*       fc2.com         
Bitsquatting    gc2.com         
Bitsquatting    dc2.com         
Bitsquatting    bc2.com         
Bitsquatting    nc2.com         
Bitsquatting    vc2.com         
Bitsquatting    fb2.com         
Bitsquatting    fa2.com         
Bitsquatting    fg2.com         
Bitsquatting    fk2.com         
Bitsquatting    fs2.com         
Bitsquatting    fc3.com         
Bitsquatting    fc0.com         
Bitsquatting    fc6.com         
Bitsquatting    fcr.com         
Repetition      ffc2.com        
Repetition      fcc2.com        
Transposition   cf2.com         
Transposition   f2c.com         
Replacement     tc2.com         
Replacement     gc2.com         
Replacement     vc2.com         
Replacement     cc2.com         
Replacement     dc2.com         
Replacement     rc2.com         
Replacement     fx2.com         
Replacement     fd2.com         
Replacement     ff2.com         
Replacement     fv2.com         
Replacement     fc3.com         
Replacement     fcw.com         
Replacement     fcq.com         
Replacement     fc1.com         
Omission        fc.com          
Omission        c2.com          
Omission        f2.com          
Hyphenation     f-c2.com        
Hyphenation     fc-2.com        
Insertion       fxc2.com        
Insertion       fcx2.com        
Insertion       fdc2.com        
Insertion       fcd2.com        
Insertion       ffc2.com        
Insertion       fcf2.com        
Insertion       fvc2.com        
Insertion       fcv2.com        
Subdomain       f.c2.com        
Subdomain       fc.2.com        
