Original*       go.com          
Bitsquatting    fo.com          
Bitsquatting    eo.com          
Bitsquatting    co.com          
Bitsquatting    oo.com          
Bitsquatting    wo.com          
Bitsquatting    gn.com          
Bitsquatting    gm.com          
Bitsquatting    gk.com          
Bitsquatting    gg.com          
Homoglyph       qo.com          
Homoglyph       g0.com          
Repetition      ggo.com         
Repetition      goo.com         
Transposition   og.com          
Replacement     yo.com          
Replacement     ho.com          
Replacement     bo.com          
Replacement     vo.com          
Replacement     fo.com          
Replacement     to.com          
Replacement     g0.com          
Replacement     gp.com          
Replacement     gl.com          
Replacement     gk.com          
Replacement     gi.com          
Replacement     g9.com          
Omission        g.com           
Omission        o.com           
Hyphenation     g-o.com         
Subdomain       g.o.com         
