Original*       google.ru       
Bitsquatting    foogle.ru       
Bitsquatting    eoogle.ru       
Bitsquatting    coogle.ru       
Bitsquatting    ooogle.ru       
Bitsquatting    woogle.ru       
Bitsquatting    gnogle.ru       
Bitsquatting    gmogle.ru       
Bitsquatting    gkogle.ru       
Bitsquatting    ggogle.ru       
Bitsquatting    gongle.ru       
Bitsquatting    gomgle.ru       
Bitsquatting    gokgle.ru       
Bitsquatting    goggle.ru       
Bitsquatting    goofle.ru       
Bitsquatting    gooele.ru       
Bitsquatting    goocle.ru       
Bitsquatting    gooole.ru       
Bitsquatting    goowle.ru       
Bitsquatting    googme.ru       
Bitsquatting    googne.ru       
Bitsquatting    googhe.ru       
Bitsquatting    googde.ru       
Bitsquatting    googld.ru       
Bitsquatting    googlg.ru       
Bitsquatting    googla.ru       
Bitsquatting    googlm.ru       
Bitsquatting    googlu.ru       
Homoglyph       gooqle.ru       
Homoglyph       go0qle.ru       
Homoglyph       g00qie.ru       
Homoglyph       gooq1e.ru       
Homoglyph       g0ogle.ru       
Homoglyph       q0ogle.ru       
Homoglyph       g00gle.ru       
Homoglyph       go0qie.ru       
Homoglyph       g00qle.ru       
Homoglyph       q00qle.ru       
Homoglyph       qoogle.ru       
Homoglyph       go0gle.ru       
Homoglyph       goog1e.ru       
Homoglyph       q00gle.ru       
Homoglyph       q00qie.ru       
Homoglyph       googie.ru       
Homoglyph       gooqie.ru       
Homoglyph       g00q1e.ru       
Homoglyph       q00q1e.ru       
Homoglyph       go0q1e.ru       
Repetition      googgle.ru      
Repetition      ggoogle.ru      
Repetition      googlle.ru      
Repetition      googlee.ru      
Repetition      gooogle.ru      
Transposition   ogogle.ru       
Transposition   gogole.ru       
Transposition   goolge.ru       
Transposition   googel.ru       
Replacement     yoogle.ru       
Replacement     hoogle.ru       
Replacement     boogle.ru       
Replacement     voogle.ru       
Replacement     foogle.ru       
Replacement     toogle.ru       
Replacement     g0ogle.ru       
Replacement     gpogle.ru       
Replacement     glogle.ru       
Replacement     gkogle.ru       
Replacement     giogle.ru       
Replacement     g9ogle.ru       
Replacement     go0gle.ru       
Replacement     gopgle.ru       
Replacement     golgle.ru       
Replacement     gokgle.ru       
Replacement     goigle.ru       
Replacement     go9gle.ru       
Replacement     gooyle.ru       
Replacement     goohle.ru       
Replacement     gooble.ru       
Replacement     goovle.ru       
Replacement     goofle.ru       
Replacement     gootle.ru       
Replacement     googke.ru       
Replacement     googoe.ru       
Replacement     googpe.ru       
Replacement     googl4.ru       
Replacement     googlr.ru       
Replacement     googld.ru       
Replacement     googls.ru       
Replacement     googlw.ru       
Replacement     googl3.ru       
Omission        googl.ru        
Omission        goole.ru        
Omission        oogle.ru        
Omission        googe.ru        
Omission        gogle.ru        
Hyphenation     g-oogle.ru      
Hyphenation     go-ogle.ru      
Hyphenation     goo-gle.ru      
Hyphenation     goog-le.ru      
Hyphenation     googl-e.ru      
Insertion       g0oogle.ru      
Insertion       go0ogle.ru      
Insertion       gpoogle.ru      
Insertion       gopogle.ru      
Insertion       gloogle.ru      
Insertion       gologle.ru      
Insertion       gkoogle.ru      
Insertion       gokogle.ru      
Insertion       gioogle.ru      
Insertion       goiogle.ru      
Insertion       g9oogle.ru      
Insertion       go9ogle.ru      
Insertion       go0ogle.ru      
Insertion       goo0gle.ru      
Insertion       gopogle.ru      
Insertion       goopgle.ru      
Insertion       gologle.ru      
Insertion       goolgle.ru      
Insertion       gokogle.ru      
Insertion       gookgle.ru      
Insertion       goiogle.ru      
Insertion       gooigle.ru      
Insertion       go9ogle.ru      
Insertion       goo9gle.ru      
Insertion       gooygle.ru      
Insertion       googyle.ru      
Insertion       goohgle.ru      
Insertion       googhle.ru      
Insertion       goobgle.ru      
Insertion       googble.ru      
Insertion       goovgle.ru      
Insertion       googvle.ru      
Insertion       goofgle.ru      
Insertion       googfle.ru      
Insertion       gootgle.ru      
Insertion       googtle.ru      
Insertion       googkle.ru      
Insertion       googlke.ru      
Insertion       googole.ru      
Insertion       googloe.ru      
Insertion       googple.ru      
Insertion       googlpe.ru      
Subdomain       g.oogle.ru      
Subdomain       go.ogle.ru      
Subdomain       goo.gle.ru      
Subdomain       goog.le.ru      
Subdomain       googl.e.ru      
