Original*       jd.com          
Bitsquatting    kd.com          
Bitsquatting    hd.com          
Bitsquatting    nd.com          
Bitsquatting    bd.com          
Bitsquatting    zd.com          
Bitsquatting    je.com          
Bitsquatting    jf.com          
Bitsquatting    jl.com          
Bitsquatting    jt.com          
Homoglyph       jb.com          
Homoglyph       jcl.com         
Repetition      jdd.com         
Repetition      jjd.com         
Transposition   dj.com          
Replacement     id.com          
Replacement     kd.com          
Replacement     md.com          
Replacement     nd.com          
Replacement     hd.com          
Replacement     ud.com          
Replacement     jr.com          
Replacement     jf.com          
Replacement     jc.com          
Replacement     jx.com          
Replacement     js.com          
Replacement     je.com          
Omission        d.com           
Omission        j.com           
Hyphenation     j-d.com         
Subdomain       j.d.com         
