Original*       kat.cr          
Bitsquatting    jat.cr          
Bitsquatting    iat.cr          
Bitsquatting    oat.cr          
Bitsquatting    cat.cr          
Bitsquatting    kct.cr          
Bitsquatting    ket.cr          
Bitsquatting    kit.cr          
Bitsquatting    kqt.cr          
Bitsquatting    kau.cr          
Bitsquatting    kav.cr          
Bitsquatting    kap.cr          
Bitsquatting    kad.cr          
Bitsquatting    ka4.cr          
Repetition      kkat.cr         
Repetition      kaat.cr         
Repetition      katt.cr         
Transposition   akt.cr          
Transposition   kta.cr          
Replacement     oat.cr          
Replacement     lat.cr          
Replacement     mat.cr          
Replacement     jat.cr          
Replacement     iat.cr          
Replacement     kqt.cr          
Replacement     kwt.cr          
Replacement     kst.cr          
Replacement     kzt.cr          
Replacement     ka6.cr          
Replacement     kay.cr          
Replacement     kag.cr          
Replacement     kaf.cr          
Replacement     kar.cr          
Replacement     ka5.cr          
Omission        at.cr           
Omission        ka.cr           
Omission        kt.cr           
Hyphenation     k-at.cr         
Hyphenation     ka-t.cr         
Insertion       kqat.cr         
Insertion       kaqt.cr         
Insertion       kwat.cr         
Insertion       kawt.cr         
Insertion       ksat.cr         
Insertion       kast.cr         
Insertion       kzat.cr         
Insertion       kazt.cr         
Subdomain       k.at.cr         
Subdomain       ka.t.cr         
