Original*       mail.ru         
Bitsquatting    lail.ru         
Bitsquatting    oail.ru         
Bitsquatting    iail.ru         
Bitsquatting    eail.ru         
Bitsquatting    mcil.ru         
Bitsquatting    meil.ru         
Bitsquatting    miil.ru         
Bitsquatting    mqil.ru         
Bitsquatting    mahl.ru         
Bitsquatting    makl.ru         
Bitsquatting    maml.ru         
Bitsquatting    maal.ru         
Bitsquatting    mayl.ru         
Bitsquatting    maim.ru         
Bitsquatting    main.ru         
Bitsquatting    maih.ru         
Bitsquatting    maid.ru         
Homoglyph       ma1l.ru         
Homoglyph       nrnail.ru       
Homoglyph       nnail.ru        
Homoglyph       mall.ru         
Homoglyph       maii.ru         
Homoglyph       mali.ru         
Homoglyph       mai1.ru         
Homoglyph       mal1.ru         
Homoglyph       nail.ru         
Repetition      maill.ru        
Repetition      maail.ru        
Repetition      mmail.ru        
Repetition      maiil.ru        
Transposition   amil.ru         
Transposition   mial.ru         
Transposition   mali.ru         
Replacement     nail.ru         
Replacement     jail.ru         
Replacement     kail.ru         
Replacement     mqil.ru         
Replacement     mwil.ru         
Replacement     msil.ru         
Replacement     mzil.ru         
Replacement     ma9l.ru         
Replacement     maol.ru         
Replacement     makl.ru         
Replacement     majl.ru         
Replacement     maul.ru         
Replacement     ma8l.ru         
Replacement     maik.ru         
Replacement     maio.ru         
Replacement     maip.ru         
Omission        mil.ru          
Omission        ail.ru          
Omission        mai.ru          
Omission        mal.ru          
Hyphenation     m-ail.ru        
Hyphenation     ma-il.ru        
Hyphenation     mai-l.ru        
Insertion       mqail.ru        
Insertion       maqil.ru        
Insertion       mwail.ru        
Insertion       mawil.ru        
Insertion       msail.ru        
Insertion       masil.ru        
Insertion       mzail.ru        
Insertion       mazil.ru        
Insertion       ma9il.ru        
Insertion       mai9l.ru        
Insertion       maoil.ru        
Insertion       maiol.ru        
Insertion       makil.ru        
Insertion       maikl.ru        
Insertion       majil.ru        
Insertion       maijl.ru        
Insertion       mauil.ru        
Insertion       maiul.ru        
Insertion       ma8il.ru        
Insertion       mai8l.ru        
Subdomain       m.ail.ru        
Subdomain       ma.il.ru        
Subdomain       mai.l.ru        
