Original*       msn.com         
Bitsquatting    lsn.com         
Bitsquatting    osn.com         
Bitsquatting    isn.com         
Bitsquatting    esn.com         
Bitsquatting    mrn.com         
Bitsquatting    mqn.com         
Bitsquatting    mwn.com         
Bitsquatting    mcn.com         
Bitsquatting    m3n.com         
Bitsquatting    mso.com         
Bitsquatting    msl.com         
Bitsquatting    msj.com         
Bitsquatting    msf.com         
Homoglyph       nrnsn.com       
Homoglyph       nnsn.com        
Homoglyph       msm.com         
Homoglyph       nsn.com         
Repetition      msnn.com        
Repetition      mssn.com        
Repetition      mmsn.com        
Transposition   smn.com         
Transposition   mns.com         
Replacement     nsn.com         
Replacement     jsn.com         
Replacement     ksn.com         
Replacement     men.com         
Replacement     mdn.com         
Replacement     mxn.com         
Replacement     mzn.com         
Replacement     man.com         
Replacement     mwn.com         
Replacement     msb.com         
Replacement     msh.com         
Replacement     msj.com         
Replacement     msm.com         
Omission        sn.com          
Omission        mn.com          
Omission        ms.com          
Hyphenation     m-sn.com        
Hyphenation     ms-n.com        
Insertion       mesn.com        
Insertion       msen.com        
Insertion       mdsn.com        
Insertion       msdn.com        
Insertion       mxsn.com        
Insertion       msxn.com        
Insertion       mzsn.com        
Insertion       mszn.com        
Insertion       masn.com        
Insertion       msan.com        
Insertion       mwsn.com        
Insertion       mswn.com        
Subdomain       m.sn.com        
Subdomain       ms.n.com        
