Original*       ok.ru           
Bitsquatting    nk.ru           
Bitsquatting    mk.ru           
Bitsquatting    kk.ru           
Bitsquatting    gk.ru           
Bitsquatting    oj.ru           
Bitsquatting    oi.ru           
Bitsquatting    oo.ru           
Bitsquatting    oc.ru           
Homoglyph       0k.ru           
Repetition      ook.ru          
Repetition      okk.ru          
Transposition   ko.ru           
Replacement     0k.ru           
Replacement     pk.ru           
Replacement     lk.ru           
Replacement     kk.ru           
Replacement     ik.ru           
Replacement     9k.ru           
Replacement     oo.ru           
Replacement     ol.ru           
Replacement     om.ru           
Replacement     oj.ru           
Replacement     oi.ru           
Omission        o.ru            
Omission        k.ru            
Hyphenation     o-k.ru          
Subdomain       o.k.ru          
