Original*       qq.com          
Bitsquatting    pq.com          
Bitsquatting    sq.com          
Bitsquatting    uq.com          
Bitsquatting    yq.com          
Bitsquatting    aq.com          
Bitsquatting    1q.com          
Bitsquatting    qp.com          
Bitsquatting    qs.com          
Bitsquatting    qu.com          
Bitsquatting    qy.com          
Bitsquatting    qa.com          
Bitsquatting    q1.com          
Homoglyph       gq.com          
Homoglyph       qg.com          
Repetition      qqq.com         
Replacement     1q.com          
Replacement     2q.com          
Replacement     wq.com          
Replacement     aq.com          
Replacement     q1.com          
Replacement     q2.com          
Replacement     qw.com          
Replacement     qa.com          
Omission        q.com           
Hyphenation     q-q.com         
Subdomain       q.q.com         
