Original*       vk.com          
Bitsquatting    wk.com          
Bitsquatting    tk.com          
Bitsquatting    rk.com          
Bitsquatting    fk.com          
Bitsquatting    6k.com          
Bitsquatting    vj.com          
Bitsquatting    vi.com          
Bitsquatting    vo.com          
Bitsquatting    vc.com          
Repetition      vvk.com         
Repetition      vkk.com         
Transposition   kv.com          
Replacement     ck.com          
Replacement     fk.com          
Replacement     gk.com          
Replacement     bk.com          
Replacement     vo.com          
Replacement     vl.com          
Replacement     vm.com          
Replacement     vj.com          
Replacement     vi.com          
Omission        v.com           
Omission        k.com           
Hyphenation     v-k.com         
Subdomain       v.k.com         
