Original*       yahoo.com       
Bitsquatting    xahoo.com       
Bitsquatting    qahoo.com       
Bitsquatting    iahoo.com       
Bitsquatting    9ahoo.com       
Bitsquatting    ychoo.com       
Bitsquatting    yehoo.com       
Bitsquatting    yihoo.com       
Bitsquatting    yqhoo.com       
Bitsquatting    yaioo.com       
Bitsquatting    yajoo.com       
Bitsquatting    yaloo.com       
Bitsquatting    yaxoo.com       
Bitsquatting    yahno.com       
Bitsquatting    yahmo.com       
Bitsquatting    yahko.com       
Bitsquatting    yahgo.com       
Bitsquatting    yahon.com       
Bitsquatting    yahom.com       
Bitsquatting    yahok.com       
Bitsquatting    yahog.com       
Homoglyph       yah00.com       
Homoglyph       yah0o.com       
Homoglyph       yaho0.com       
Repetition      yaahoo.com      
Repetition      yyahoo.com      
Repetition      yahooo.com      
Repetition      yahhoo.com      
Transposition   ayhoo.com       
Transposition   yhaoo.com       
Transposition   yaoho.com       
Replacement     7ahoo.com       
Replacement     uahoo.com       
Replacement     hahoo.com       
Replacement     gahoo.com       
Replacement     tahoo.com       
Replacement     6ahoo.com       
Replacement     yqhoo.com       
Replacement     ywhoo.com       
Replacement     yshoo.com       
Replacement     yzhoo.com       
Replacement     yauoo.com       
Replacement     yajoo.com       
Replacement     yanoo.com       
Replacement     yaboo.com       
Replacement     yagoo.com       
Replacement     yayoo.com       
Replacement     yah0o.com       
Replacement     yahpo.com       
Replacement     yahlo.com       
Replacement     yahko.com       
Replacement     yahio.com       
Replacement     yah9o.com       
Replacement     yaho0.com       
Replacement     yahop.com       
Replacement     yahol.com       
Replacement     yahok.com       
Replacement     yahoi.com       
Replacement     yaho9.com       
Omission        ahoo.com        
Omission        yhoo.com        
Omission        yaho.com        
Omission        yaoo.com        
Hyphenation     y-ahoo.com      
Hyphenation     ya-hoo.com      
Hyphenation     yah-oo.com      
Hyphenation     yaho-o.com      
Insertion       yqahoo.com      
Insertion       yaqhoo.com      
Insertion       ywahoo.com      
Insertion       yawhoo.com      
Insertion       ysahoo.com      
Insertion       yashoo.com      
Insertion       yzahoo.com      
Insertion       yazhoo.com      
Insertion       yauhoo.com      
Insertion       yahuoo.com      
Insertion       yajhoo.com      
Insertion       yahjoo.com      
Insertion       yanhoo.com      
Insertion       yahnoo.com      
Insertion       yabhoo.com      
Insertion       yahboo.com      
Insertion       yaghoo.com      
Insertion       yahgoo.com      
Insertion       yayhoo.com      
Insertion       yahyoo.com      
Insertion       yah0oo.com      
Insertion       yaho0o.com      
Insertion       yahpoo.com      
Insertion       yahopo.com      
Insertion       yahloo.com      
Insertion       yaholo.com      
Insertion       yahkoo.com      
Insertion       yahoko.com      
Insertion       yahioo.com      
Insertion       yahoio.com      
Insertion       yah9oo.com      
Insertion       yaho9o.com      
Subdomain       y.ahoo.com      
Subdomain       ya.hoo.com      
Subdomain       yah.oo.com      
Subdomain       yaho.o.com      
