Original*       yandex.ru       
Bitsquatting    xandex.ru       
Bitsquatting    qandex.ru       
Bitsquatting    iandex.ru       
Bitsquatting    9andex.ru       
Bitsquatting    ycndex.ru       
Bitsquatting    yendex.ru       
Bitsquatting    yindex.ru       
Bitsquatting    yqndex.ru       
Bitsquatting    yaodex.ru       
Bitsquatting    yaldex.ru       
Bitsquatting    yajdex.ru       
Bitsquatting    yafdex.ru       
Bitsquatting    yaneex.ru       
Bitsquatting    yanfex.ru       
Bitsquatting    yanlex.ru       
Bitsquatting    yantex.ru       
Bitsquatting    yanddx.ru       
Bitsquatting    yandgx.ru       
Bitsquatting    yandax.ru       
Bitsquatting    yandmx.ru       
Bitsquatting    yandux.ru       
Bitsquatting    yandey.ru       
Bitsquatting    yandez.ru       
Bitsquatting    yandep.ru       
Bitsquatting    yandeh.ru       
Bitsquatting    yande8.ru       
Homoglyph       yambex.ru       
Homoglyph       yamclex.ru      
Homoglyph       yanbex.ru       
Homoglyph       yanclex.ru      
Homoglyph       yamdex.ru       
Repetition      yandexx.ru      
Repetition      yaandex.ru      
Repetition      yanndex.ru      
Repetition      yyandex.ru      
Repetition      yandeex.ru      
Repetition      yanddex.ru      
Transposition   ayndex.ru       
Transposition   ynadex.ru       
Transposition   yadnex.ru       
Transposition   yanedx.ru       
Transposition   yandxe.ru       
Replacement     7andex.ru       
Replacement     uandex.ru       
Replacement     handex.ru       
Replacement     gandex.ru       
Replacement     tandex.ru       
Replacement     6andex.ru       
Replacement     yqndex.ru       
Replacement     ywndex.ru       
Replacement     ysndex.ru       
Replacement     yzndex.ru       
Replacement     yabdex.ru       
Replacement     yahdex.ru       
Replacement     yajdex.ru       
Replacement     yamdex.ru       
Replacement     yanrex.ru       
Replacement     yanfex.ru       
Replacement     yancex.ru       
Replacement     yanxex.ru       
Replacement     yansex.ru       
Replacement     yaneex.ru       
Replacement     yand4x.ru       
Replacement     yandrx.ru       
Replacement     yanddx.ru       
Replacement     yandsx.ru       
Replacement     yandwx.ru       
Replacement     yand3x.ru       
Replacement     yandez.ru       
Replacement     yandes.ru       
Replacement     yanded.ru       
Replacement     yandec.ru       
Omission        yandx.ru        
Omission        andex.ru        
Omission        yadex.ru        
Omission        yndex.ru        
Omission        yanex.ru        
Omission        yande.ru        
Hyphenation     y-andex.ru      
Hyphenation     ya-ndex.ru      
Hyphenation     yan-dex.ru      
Hyphenation     yand-ex.ru      
Hyphenation     yande-x.ru      
Insertion       yqandex.ru      
Insertion       yaqndex.ru      
Insertion       ywandex.ru      
Insertion       yawndex.ru      
Insertion       ysandex.ru      
Insertion       yasndex.ru      
Insertion       yzandex.ru      
Insertion       yazndex.ru      
Insertion       yabndex.ru      
Insertion       yanbdex.ru      
Insertion       yahndex.ru      
Insertion       yanhdex.ru      
Insertion       yajndex.ru      
Insertion       yanjdex.ru      
Insertion       yamndex.ru      
Insertion       yanmdex.ru      
Insertion       yanrdex.ru      
Insertion       yandrex.ru      
Insertion       yanfdex.ru      
Insertion       yandfex.ru      
Insertion       yancdex.ru      
Insertion       yandcex.ru      
Insertion       yanxdex.ru      
Insertion       yandxex.ru      
Insertion       yansdex.ru      
Insertion       yandsex.ru      
Insertion       yanedex.ru      
Insertion       yandeex.ru      
Insertion       yand4ex.ru      
Insertion       yande4x.ru      
Insertion       yandrex.ru      
Insertion       yanderx.ru      
Insertion       yanddex.ru      
Insertion       yandedx.ru      
Insertion       yandsex.ru      
Insertion       yandesx.ru      
Insertion       yandwex.ru      
Insertion       yandewx.ru      
Insertion       yand3ex.ru      
Insertion       yande3x.ru      
Subdomain       y.andex.ru      
Subdomain       ya.ndex.ru      
Subdomain       yan.dex.ru      
Subdomain       yand.ex.ru      
Subdomain       yande.x.ru      
